'------------------------------------------------------------------------------
' <auto-generated>
'     Este código lo generó una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class cambioPass

	'''<summary>
	'''control form1.
	'''</summary>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	Protected WithEvents lblNueva As Global.System.Web.UI.WebControls.Label
	Protected WithEvents txtNuevaClave As Global.System.Web.UI.WebControls.TextBox
	Protected WithEvents lblRepetir As Global.System.Web.UI.WebControls.Label
	Protected WithEvents txtRepetirClave As Global.System.Web.UI.WebControls.TextBox
	Protected WithEvents btnCambiar As Global.System.Web.UI.WebControls.Button
	Protected WithEvents pnlMensaje As Global.System.Web.UI.WebControls.Panel
	Protected WithEvents litMensaje As Global.System.Web.UI.WebControls.Literal
End Class
